servers:
- google.com 
- yandex.ru
- instagram.com
- error
- google342325235.com
- youtube.com
- mail.ru
- apple.com
- microsoft.com
- stackoverflow.com
- twitter.com

host: "localhost"
port: 5432
database: "status"
httptimeout_ms: 2000
user: postgres
pass: 1977perplex